### ISSUE TITLE
Support for "fields" metadata attribute is missing

### ISSUE THREAD

**Issue by nuttamsingh** [splunk/splunk-javascript-logging#47] opened 2021-02-09 00:58 UTC
Based on the documentation of the event metadata types in 8.1.1 
https://docs.splunk.com/Documentation/Splunk/8.1.1/Data/FormateventsforHTTPEventCollector

Thanks!

**Comment by Rahmo** [comment] 2021-05-04 19:23
it doesn't work for me either

**Comment by Rahmo** [comment] 2021-05-04 22:16
looking at the code I think the problem is in here 
https://github.com/splunk/splunk-javascript-logging/blob/master/splunklogger.js#L353
something about the return I would put it inside the if

**Comment by bparmar-splunk** [comment] 2022-09-29 04:46
Hi All,
Closing this issue because PR #70 supporting this issue has been merged.

Thank you.

**Closed by bparmar-splunk** 2022-09-29 04:46 UTC
